column_width = 112
line_endings = "Unix"
indent_type = "Spaces"  # Tabs, Spaces
indent_width = 2
quote_style = "AutoPreferDouble"  # AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle
# call_parentheses = "Always"  # Always, NoSingleString, NoSingleTable, None
