require("user.options")
require("user.autocommands")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")

require("user.nvim_tree")
require("user.cmp")
require("user.lsp")

require("user.bufferline")
require("user.lualine")
require("user.treesitter")
require("user.telescope")
require("user.impatient")
require("user.comment")
require("user.whichkey")
require("user.alpha")
require("user.autopairs")
require("user.hop")
require("user.trouble")
require("user.project")
require("user.gitsigns")
require("user.dap")
require("user.indent_blankline")
require("user.flutter_tools")
require("user.toggleterm")
-- require("user.illuminate_settings")
require("user.auto_session")
require("user.session_lens")
