require("user.options")
require("user.keymaps")

require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")

require("user.bufferline")
require("user.lualine")
require("user.treesitter")
require("user.telescope")
require("user.impatient")
require("user.comment")
require("user.whichkey")
require("user.alpha")
require("user.autopairs")
require("user.hop")
-- require "user.lightspeed"
require("user.trouble")
require("user.project")
require("user.gitsigns")
